name: despesas_pessoais
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  rxdart: ^0.26.0
  mask_text_input_formatter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/images/waiting.png
    
fonts:
  - family: OpenSans
    fonts: 
    - asset: assetsfonts/Schyler-Regular.ttf
    - asset: assetsfonts/Schyler-Bold.ttf
      weight: 700
  - family: Quicksand
    fonts: 
    - asset: assetsfonts/Quicksand-Regular.ttf
    - asset: assetsfonts/Quicksand-Bold.ttf
      weight: 700

 